
CREATE DATABASE IF NOT EXISTS fiap;
USE fiap;


CREATE TABLE Users (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL
);


CREATE TABLE Chats (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT NOT NULL,
    LastMessageId INT NULL,
    LastPromptId INT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);


CREATE TABLE Messages (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Text VARCHAR(500) NOT NULL,
    IsFromUser BOOLEAN NOT NULL,
    ChatId INT NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChatId) REFERENCES Chats(Id)
);

CREATE TABLE Prompts (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Text VARCHAR(500) NOT NULL,
    RelatedMessageId INT NULL,
    ChatId INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ChatId) REFERENCES Chats(Id),
    FOREIGN KEY (RelatedMessageId) REFERENCES Messages(Id)
);












